### PR TITLE
typo 'apply apply'

### PR DESCRIPTION
**Pull request by kdejaeger**

### CODE REVIEW

**Comment by kdejaeger** [comment]
Ow, better not give me access yet. Because my github skills are quite noob-like.

**Comment by jean-emmanuel** [comment]
What do you mean ? You only have write access to your fork, no chance of breaking anything here.

**Comment by kdejaeger** [comment]
I don't know it looked form this page, as if my change was merged into yours and travis was building.

**Comment by jean-emmanuel** [comment]
Travis does a test build indeed.

**Pull request merged**
