### PR TITLE
make room for debug panel

### PR DESCRIPTION
**Pull request by kdejaeger**

### CODE REVIEW

**Comment by kdejaeger** [comment]
room

**Comment by kdejaeger** [comment]
On my PC, I could not see the debug window. Well, it was like 0,5 rows high, I always had to enlarge the window.

**Comment by jean-emmanuel** [comment]
Hmm, there might be a more elegant way to handle that, I'll try something soon. Thanks for the typo, funny indeed. Please consider opening a different pull request for each problem you intent to fix.

**Comment by jean-emmanuel** [comment]
4181765 fixes it.

**Pull request closed without merging**
