### PR TITLE
WIP  : editor traversing shortcuts

### PR DESCRIPTION
**Pull request by MartinHN**
this allow to quickly change selected widget in editor
mostly needed when having panel without label : the panel is "invisible" so selecting one or the other has to be done via side panel...

mod + up/down => edit parent / child
mod + left / right => edit siblings

this PR looks functional to me but is still marked as WIP because : 

* the way I have to resolve child objects is kind of hacky because getProps('widgets') return Object (not widgets) without the hash info so I have to identify them by asserting equality with ('id','top','left','right') although even in case of multiple object sharing these, it wont generate bug

* another way is to use childrenHashes, but its filled with nested childrens too

* to navigate through siblings i use widget.container.offsetLeft, not sure thats the best though...

### CODE REVIEW

**Comment by jean-emmanuel** [comment]
That's cool !! I'll try to review it today

**Comment by MartinHN** [comment]
now implementation is cleaner (use hashes directly)

**Comment by MartinHN** [comment]
one remaining problem to use this pr at its full potential,
once a panel is selected, right clicking on it (hovering a widget inside) will trigger selection of the widget inside.
I realize right now thats a bigger conceptual problem. 
as right click should allow selecting at the same time,  let me know if you see a way out.
may be a keyboard shortcut, allowing to trigger context menu for the current selected item

**Comment by jean-emmanuel** [comment]
Holding ctrl (or command on mac) prevents right click from changing current selectiong, it seems some file managers behave this way too, although it's hard to get an actual standard on this.

**Comment by MartinHN** [comment]
great, so it's working that way, (well its not cmd but ctrl on mac)

**Comment by jean-emmanuel** [comment]
I just checked the code, it'd set shiftKey for mac. Is it ctrl for multiple selection too ?

**Comment by MartinHN** [comment]
for the ctrl key I think the relevant code is in app/editor/context-menu.js l:152

if (!event.detail.ctrlKey && editor.selectedWidgets.length <= 1) { ...

**Comment by jean-emmanuel** [comment]
Looks like an error, it should use the key defined in line 8:
`var mod = (navigator.platform || '').match('Mac') ? 'shiftKey' : 'ctrlKey'`
But still I'd need to figure out what'd be the expected key for mac users

**Comment by MartinHN** [comment]
well for now mod is used for multi selection, and ctrl to avoir triggering selection, personally I find this behaviour quite ok. let me know if you come with a finer solution

**Comment by MartinHN** [comment]
sorry, the problem is then on other platforms than mac, just got it...

**Comment by jean-emmanuel** [comment]
On other platform it's `ctrl` for both, but it's not a problem, other softwares seem to behave that way. My concern was more about consistency with other mac softwares.

**Comment by jean-emmanuel** [comment]
Ok I changed that key to `mod` (`ctrl` / `command` on mac) for consistency. Right-click leaves the selection untouched if:
- there is only 1 widget in selection and `shift` is hold
- there is more than 1 widget in selection 

Note that `shift` also enables lasso selection.

**Pull request merged**
