### PR TITLE
src: typos and grammatical (English) cleanups. 

### PR DESCRIPTION
**Pull request by erictheise**
I've restricted my changes to comments, help, and error messages.

### CODE REVIEW

**Comment by erictheise** [comment]
@jean-emmanuel, there are a few occurrences of the world __catched__ in the code and I wasn't positive whether you meant __cached__ or __caught__ but if you clarify I'd be happy to add the correct change to this PR.

**Comment by erictheise** [comment]
My IDE caught two other typos that are functional:

 - `x-positionned` and `y-positionned` should have a single 'n'.
 - `fullscreen_unnavailable` should also have a single 'n'.

Happy to change those in this PR as well, just let me know @jean-emmanuel.

**Comment by jean-emmanuel** [comment]
All occurences of "catched" can be corrected to "caught". 

> Happy to change those in this PR as well, just let me know @jean-emmanuel.

Yes, please :)

**Comment by jean-emmanuel** [comment]
Thanks :)

**Pull request merged**
