### PR TITLE
Example: Muse headset

### PR DESCRIPTION
**Pull request by alx**
Connect Muse headset - http://www.choosemuse.com/ - to Open Stage Control, thanks to Muse Monitor app : http://musemonitor.com/

Howto:

1. Launch open-stage-control, and get/set the osc host:port to be used
2. Launch Muse Monitor on your ios/android
3. Setup osc settings with open-stage-control osc host:port
4. Click on osc streaming button
5. Open muse example in open-stage-control

### CODE REVIEW

**Comment by alx** [comment]
Here is a screenshot of it running:

2017-08-31-002316_1366x768_scrot

**Comment by jean-emmanuel** [comment]
Hi ! Thanks for your pull request and you interest in the project ! As happy as I am to see usage examples out here, I'm afraid this one is really too specific to be packaged with the app, maybe I should set up a more open example sessions bank online where this would better fit.

**Comment by alx** [comment]
Thanks @jean-emmanuel for your feedback, I fully understand how it's too specific to be packaged, and I'm closing this issue.

I also wanted to thank you a lot for this wonderful software and code.
It's been a visual pleasure to play with it, and an interesting clean-code reading.

**Comment by cyberic99** [comment]
Hello!
Just wanted to say that even if this file is specific to an hardware device, it can still serve as an example.
For instance, when I saw the screenshot, I wanted to know how it had been done, and looked at the .js file.
I even think that the old 'demo' files that were available by default previously, were useful, in order to achieve the 'Wow effect', in order to get an idea of what can be achieved with o-s-c.
But I agree that if this specific file is packaged with the app, there will be an additional maintenance cost.

Anyway, thanks for your work, @jean-emmanuel !

**Comment by alx** [comment]
@cyberic99 you bring an interesting point, I found screenshots (general ones, and one per widget) were missing in the documentation.

I might make another PR if I find some time to make these screenshots.

Have a nice day :)

**Comment by jean-emmanuel** [comment]
Thanks for your feedback guys !

Making nice screenshots takes time indeed, the docs could use some I agree;

**Pull request closed without merging**
