### PR TITLE
WIP dynamic props

### PR DESCRIPTION
**Pull request by MartinHN**
another refactor, (I can't stand the 10 second waiting that all clones refresh)
I just tried to use prop-changed events to avoid reconstructing every thing from scratch at every small changes (like moving stuff around)

tests 
on this sketch [LGMLTemplate.json.zip](https://github.com/jean-emmanuel/open-stage-control/files/2489783/LGMLTemplate.json.zip)
 show a vast improvement in reactivity!

Again, it may break things, it's just to start a discussion...

the main problem if we unify property setters and event system is that,when working with clones with dynamic Ids we usually want some property shared even if they have different computed ids (position/colors...), and some not (the ones depending on OSC messages representing state particular to each instance)
I choosed arbitrarily to propagate property changes between clones only if they are coming from the editor (moving or using side panel) I think thats a good middle ground, what do you think?

secondly I included also a kind of detection that prevent rebuilding in updatewidget function if only dynamicProps are changed, it may be redundant with the existing reUse flag that I haven't got until now, it may be removed if judged useless at the end

### CODE REVIEW

**Comment by jean-emmanuel** [comment]
It's a bit hard to review, there seem to be many changes that don't relate the PR; I'll take a look a it ! Have you tried the big set of changes I pushed yesterday, it also made editing things much smoother.

**Comment by MartinHN** [comment]
well commit history is a mess I can clean it and open a new PR, I just realize now, but changes are not that big

**Comment by jean-emmanuel** [comment]
I've thinking about this and to be honest I'd prefer to avoid extending prop-updates to the editor, it makes things much more complex only for the clone widget. Instead, I think it's possible to have the clone handle updates differently for a similar result. Actually I have something that starts to work nicely, I'll open a PR so that we can try it.

**Comment by jean-emmanuel** [comment]
Check it out https://github.com/jean-emmanuel/open-stage-control/pull/392

**Pull request closed without merging**
